# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b9534f6802849c2f3679dafdc5f7950bb745900362233f8891555855d51d90ffe338736db25f3f1409e7a6ab2a6cc0248083343f9d2d04f72533cd4d31946ea

test:
  secret_key_base: 6c2a376f65a51221e0aa07e3c4991db1c6bcbfa02e841fe01aca3e2881c10ad953066f06e1163ae01eb63492e0305d75bcbc2c5d2fe563f95f247a047f1d7b22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
